TemplateFormatVersion: 2024-02-10
Description: config sample of lowcode-lambda with go

Server:
  Port: 8081

Resources:
  WhatsAppAuth:
    ResourceType: Endpoint
    Description: Simulação da autenticação do WhatsApp Business API
    Properties:
      Path: /v19.0/oauth/access_token
      Method: POST
      Response:
        StatusCode: 200
        Content: responses/auth.json

  WhatsAppMessage:
    ResourceType: Endpoint
    Description: Simulação do envio de mensagens do WhatsApp Business API
    Properties:
      Path: /v19.0/:phone_number/messages
      Method: POST
      Response:
        StatusCode: 200
        Content: responses/message.json